#No Docker, Eureka, Config Server, Postgres

#Application
server:
  port: 8001
spring:
  application:
    name: user-service

  #H2 Datasource
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: me
    password: letmein
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  #Circuit Breaker
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

    #Config client
    config:
      enabled: false

  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#Redis
redis:
  hostname: localhost
  port: 6379

#Eureka client
eureka:
  client:
    enabled: false

#Swagger OpenApi
springdoc:
  swagger-ui:
    path: /docs

#Feign Services
services:
  media:
    name: media-service
    url: http://localhost:8003
    path: /media

#Media
defaultImage:
  url: http://localhost:${server.port}/DefaultProfileImage.png