#Server
server:
  url: http://localhost:${server.port}
project:
  path: ${user.dir}/Chat-Web/User
#Media
media:
  defaultImage:
    name: DefaultProfileImage.png
    path: src/main/resources/static/${media.defaultImage.name}
#Application
spring:
  application:
    name: user-service
  #Postgres datasource
  datasource:
    driverClassName: org.postgresql.Driver
  #Hibernate JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #Config client
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      uri: config-server
  config:
    import: optional:configserver:lb://config-server
  #Kafka Config
  kafka:
    bootstrap-servers: kafka
    properties:
      spring:
        json:
          trusted:
            packages: *
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka