#Application
server:
  port: 8001
spring:
  application:
    name: user-service

  #H2 Datasource
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: me
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#Redis
redis:
  hostname: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

#Swagger OpenApi
springdoc:
  api-docs:
    enabled: true 
    path: /user/v3/api-docs
  swagger-ui:
    enabled: true
    path: /user/swagger-ui.html

#Feign Services
services:
  media:
    name: media-service
    url: http://localhost:8003
    path: /media

#Media
defaultImage:
  name: DefaultProfileImage.png
  url: http://localhost:${server.port}/${defaultImage.name}