services:

  # Kafka
  kafka:
    image: confluentinc/confluent-local
    ports:
      - "9094:9094"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - chat-web-net
    restart: always
    healthcheck:
      test: /kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092 || exit 1
      start_period: 60s
      interval: 20s
      timeout: 10s
      retries: 5

  # Postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: letmein
    networks:
      - chat-web-net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  #Redis
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - chat-web-net
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  chat-web-net:
