services:

# Kafka Service Configuration
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL


# User Service Configuration
  user-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: letmein
      PGDATA: /data/postgres 
    volumes:
      - user-db-vol:/postgres/data
  user-redis:
    image: redis
    ports:
      - "6379"


# Social Service Configuration
  social-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: social-db
      MYSQL_USER: root 
      MYSQL_PASSWORD: letmein 
    volumes:
      - social-db-vol:/var/lib/mysql
  social-redis:
    image: redis
    ports:
      - "6380"


# Presence Service Configuration
  presence-redis:
    image: redis
    ports:
      - "6381"


# Chat Service Configuration
  chat-db:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - chat-db-vol:/var/lib/cassandra
  chat-redis:
    image: redis
    ports:
      - "6382:6382"

volumes:
  user-db-vol:
  social-db-vol:
  chat-db-vol:
