services:

  # Kafka
  kafka:
    image: confluentinc/confluent-local
    ports:
      - "9094:9094"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - chat-web-net
    restart: always

  # Postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: letmein
    networks:
      - chat-web-net
    restart: always

  #Redis
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - chat-web-net
    restart: always