services:

  #Kafka
  kafka:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 800M
    networks:
      - chat-web-net
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1
      start_period: 80s
      interval: 30s
      timeout: 10s
      retries: 5

  #Redis
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 70M
    networks:
      - chat-web-net
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
      
include:
  - Gateway/docker-compose.yaml
  - Media/docker-compose.yaml
  - User/docker-compose.yaml
  - Chat/docker-compose.yaml
  
networks:
  chat-web-net:
