services:
  gateway:
    build: Gateway/.
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
    networks:
      - chat-web-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8000/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
