services:
  gateway:
    build: .
    ports:
      - "8000:8000"
    networks:
      - chat-web-net
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8000/actuator/health"]
      start_period: 120s
      interval: 60s
      timeout: 5s
      retries: 5