services:
  chat:
    build: Chat/.
    ports:
      - "8002:8002"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      kafka:
        condition: service_healthy
      chat-db:
        condition: service_healthy
      chat-redis:
        condition: service_healthy
    networks:
      - chat-net
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8002/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
  chat-db:
    image: cassandra
