services:
  chat:
    build: .
    ports:
      - "8002:8002"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - chat-web-net
    restart: always
    depends_on:
      gateway:
        condition: service_healthy
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8002/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5