services:
  chat:
    build: .
    ports:
      - "8002:8002"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - chat-web-net
    restart: always
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      gateway:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8002/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5