#Application
spring:
  application:
    name: presence-service
  #Config client
  cloud:
    config:
      uri: configuration-service
      discovery:
        enabled: true
        serviceId: configuration-service
  config:
    import: optional:configserver:lb://configuration-service
  #Kafka Config
  kafka:
    bootstrap-servers: localhost:9094
    properties:
      spring.json.trusted.packages: *
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#Redis
redis:
  hostname: localhost
  port: 6379