#No Docker, Eureka, Config Server

#Application
server:
  port: 8000
spring:
  application:
    name: gateway-service
    
  #Config client
  cloud:
    config:
      enabled: false  
      
#Eureka client
eureka:
  client:
    enabled: false

#Swagger OpenApi
springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: user-service
        url: /users/v3/api-docs