#Application
spring:
  application:
    name: gateway-service
  #Config client
  cloud:
    config:
      uri: configuration-service
      discovery:
        enabled: true
        serviceId: config-service
  config:
    import: optional:configserver:lb://${spring.cloud.config.uri}
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka