#Application
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:configuration-service/

  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configuration-service
#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/