services:
  media:
    build: .
    ports:
      - "8005:8005"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - chat-web-net
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8005/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
