services:
  media:
    build: Media/.
    ports:
      - "8005:8005"
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - project-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8005/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5