#Server
server:
  port: 8761
#Application
spring:
  application:
    name: eureka-service
#Eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false