server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        prefix: /config
        git:
          uri: https://github.com/CsarNarciso/Chat-Web
          defaultLabel: main
          search-paths:
            - Configurations
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka