services:
  presence:
    build: .
    ports:
      - "8003:8003"
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      presence-redis:
        condition: service_healthy
    networks:
      - discovery-net
      - presence-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8003/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
  presence-redis:
    image: redis
    ports:
      - "6381:6381"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  presence-net: