services:
  presence:
    build: Presence/.
    ports:
      - "8003:8003"
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - project-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8003/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5