services:
  chat:
    image: csarnar/chat-web-chat
    ports:
      - "8004:8004"
    networks:
      - eureka-net
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      user:
        condition: service_healthy
      message:
        condition: service_healthy
      conversation:
        condition: service_healthy
      gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8004/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
