services:
  config:
    build: ConfigServer/.
    ports:
      - "8888:8888"
    networks:
      - eureka-net
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8888/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5