services:
  conversation:
    image: csarnar/chat-web-conversation
    ports:
      - "8003:8003"
    environment:
      - SPRING_DATASOURCE_URL=${CONVERSATION_API_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${CONVERSATION_API_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${CONVERSATION_API_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${CONVERSATION_API_JPA_HIBERNATE_DDL_AUTO}
    networks:
      - eureka-net
      - postgres-net
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8003/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5