services:
  discovery:
    build: Discovery/.
    ports:
      - "8761:8761"
    networks:
      - discovery-net
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8761/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  discovery-net: