services:
  gateway:
    image: csarnar/chat-web-gateway
    ports:
      - "8000:8000"
    networks:
      - eureka-net
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
      user:
        condition: service_healthy
      message:
        condition: service_healthy
      conversation:
        condition: service_healthy
      chat:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8000/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
