services:
  message:
    image: csarnar/chat-web-message
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=${MESSAGE_API_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MESSAGE_API_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MESSAGE_API_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${MESSAGE_API_JPA_HIBERNATE_DDL_AUTO}
    networks:
      - eureka-net
      - mysql-net
    depends_on:
      eureka:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8002/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
