services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db", "-U", "postgres"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-vol:/data/postgres
    networks:
      - postgres-net