services:
  presence:
    build: Presence/.
    ports:
      - "8003:8003"
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      presence-redis:
        condition: service_healthy
    networks:
      - discovery-net
      - presence-redis-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8003/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
  presence-redis:
    image: redis
    ports:
      - "8003:8003"
    env_file:
      - Presence/.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - presence-redis-net
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8003/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  presence-redis-net: