services:
  discovery:
    build: Discovery/.
    ports:
      - "8761:8761"
    networks:
      - project-net
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8761/actuator/health" ]
      start_period: 120s
      interval: 60s
      timeout: 5s
      retries: 5