services:
  discovery:
    build: .
    ports:
      - "8761:8761"
    networks:
      - chat-web-net
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8761/actuator/health"]
      start_period: 120s
      interval: 60s
      timeout: 5s
      retries: 5