#Application
server:
  port: 8003
spring:
  application:
    name: media-service
    
#Media
media:
  dirName: media
  path: ${user.dir}/${media.dirName}
  url: http://localhost:${server.port}/${media.dirName}