#No Docker, Eureka, Config Server

#Application
server:
  port: 8003
spring:
  application:
    name: media-service
    
  #Config client
  cloud:
    config:
      enabled: false
      
#Media
media:
  dirName: media
  path: ${user.dir}/${media.dirName}
  url: http://localhost:${server.port}/${media.dirName}
      
#Eureka client
eureka:
  client:
    enabled: false