#No Docker, Eureka, Config Server

#Application
spring:
  application:
    name: media-service
    
  #Config client
  cloud:
    config:
      enabled: false
      
#Server
server:
  port: 8003
  url: http://localhost:${server.port}
project:
  path: ${user.dir}/Chat-Web/Media
  
#Media
resources:
  path: src/main/resources
media:
  path: ${resources.path}/media
  absolutePath: ${project.path}/${media.path}
  url: ${server.url}/${media.path}
      
#Eureka client
eureka:
  client:
    enabled: false