#Server
server:
  url: http://localhost:${server.port}
project:
  path: ${user.dir}/Chat-Web/Media
#Media
resources:
  path: src/main/resources
media:
  path: ${resources.path}/media
  absolutePath: ${project.path}/${media.path}
  url: ${server.url}/${media.path}
#Application
spring:
  application:
    name: media-service
  #Config client
  cloud:
    config:
      uri: configuration-service
      discovery:
        enabled: true
        serviceId: ${spring.cloud.config.uri}
  config:
    import: optional:configserver:lb://${spring.cloud.config.uri}
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka