#Application
spring:
  application:
    name: user-api
  #Postgres datasource
  datasource:
    url: jdbc:postgresql://chat-web-postgres-server:5432/db
    username: root
    password: letmein
  #Hibernate JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  #Config client
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      uri: config-server
  config:
    import: optional:configserver:lb://config-server
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka