#Images resources paths
server:
  url: http://localhost:${server.port}
project:
  path: ${user.dir}/Chat-Web/ProfileImageService
images:
  mainPath: src/main/resources/images
  #For Profiles
  profile:
    path: ${images.mainPath}/profile
    absolutePath: ${project.path}/${images.profile.path}
    url: ${server.url}/${images.profile.path}
  #For Groups
  group:
    path: ${images.mainPath}/group
    absolutePath: ${project.path}/${images.group.path}
    url: ${server.url}/${images.group.path}
#Application
spring:
  application:
    name: image-service
  #Postgres datasource
  datasource:
    driverClassName: org.postgresql.Driver
  #Hibernate JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #Config client
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      uri: config-server
  config:
    import: optional:configserver:lb://config-server
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka