services:
  configuration:
    build: Configuration/.
    ports:
      - "8888:8888"
    depends_on:
      discovery:
        condition: service_healthy
    networks:
      - chat-web-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8888/actuator/health"]
      start_period: 120s
      interval: 60s
      timeout: 5s
      retries: 5