services:
  configuration:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      discovery:
        condition: service_healthy
    networks:
      - discovery-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8888/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5