services:
  configuration:
    build: .
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      discovery:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 100M
    networks:
      - chat-web-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8888/actuator/health"]
      start_period: 120s
      interval: 60s
      timeout: 5s
      retries: 5
