#Application
spring:
  application:
    name: social-service
  #Postgres datasource
  datasource:
    driverClassName: org.postgresql.Driver
  #Hibernate JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #Config client
  cloud:
    config:
      uri: config-service
      discovery:
        enabled: true
        serviceId: config-service
  config:
    import: optional:configserver:lb://${spring.cloud.config.uri}
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka