#Application
spring:
  application:
    name: social-service
  #MySQL Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/social-db
    username: root
    password: letmein
    driver-class-name: com.mysql.jdbc.Driver
  #Hibernate JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #Config client
  cloud:
    config:
      uri: configuration-service
      discovery:
        enabled: true
        serviceId: configuration-service
  config:
    import: optional:configserver:lb://configuration-service
  #Kafka Config
  kafka:
    bootstrap-servers: http://localhost:9094
    properties:
      spring:
        json:
          trusted:
            packages: *
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#Redis
redis:
  hostname: localhost
  port: 6380
#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka