#Application
spring:
  application:
    name: social-service
  #Config client
  cloud:
    config:
      uri: config-service
      discovery:
        enabled: true
        serviceId: config-service
  config:
    import: optional:configserver:lb://config-service
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka