services:
  social:
    build: .
    ports:
      - "8004:8004"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      social-db:
        condition: service_healthy
      social-redis:
        condition: service_healthy
    networks:
      - discovery-net
      - social-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8004/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
  social-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - social-net
    volumes:
      - social-db-vol:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
  social-redis:
    image: redis
    ports:
      - "6380:6380"
    networks:
      - social-net
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  social-net:
volumes:
  social-db-vol: