services:
  social:
    build: .
    ports:
      - "8004:8004"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - chat-web-net
     restart: always
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8004/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5