services:
  user:
    build:
      context: ./User/.
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      discovery:
        condition: service_healthy
      configuration:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
    networks:
      - chat-web-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8001/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5