services:
  user:
    build: .
    ports:
      - "8001:8001"
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - chat-web-net
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      gateway:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8001/actuator/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5